<a href="https://colab.research.google.com/github/izzyolejnik/Machine-Learning/blob/master/HW4/HW4PT2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

input_mat = []
s = []

input_mat.append(np.array([[1, 2, 1, 2, 4, 5],
                      [2, 4, 2, 1, 0, 3],
                      [1, 2, 4, 2, 4, 5],
                      [2, 1, 2, 1, 2, 1],
                      [1, 1, 2, 3, 1, 2]]))
s.append(2)

input_mat = np.asarray(input_mat)
s = np.asarray(s)

def find_max(input_mat):
  max_val = -1
  input_mat = input_mat.flatten();
  for val in input_mat:
    if val > max_val:
      max_val = val
  return max_val

def maxpooling2d(input_mat, s):
  input_height = input_mat.shape[1]
  input_width = input_mat.shape[2]
  size = s[0]
  stride = s[0]
  output = []

  h1 = 0
  w1 = 0
  h2 = stride
  w2 = stride

  while h2 <= input_height + 1:
    w1 = 0
    w2 = stride
    out = []
    while w2 <= input_width + 1:
      pool = input_mat[0, h1:h2, w1:w2]
      max_val = find_max(pool)
      out.append(max_val)
      w1 += stride
      w2 += stride
    output.append(out)
    h1 += stride
    h2 += stride
  
  output = np.asarray(output)
  return output

output_mat = maxpooling2d(input_mat, s)
print(output_mat)

[[4 2 5]
 [2 4 5]
 [1 3 2]]
